# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170712_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
